modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="alchemical_excellence"
version="1.0.0"
displayName="Alchemical Excellence"
credits="Created by Shane Pepperell (Sp777/OfficiallySp)"
displayURL="https://officiallysp.net"
authors="OfficiallySp"
description='''
Endgame Nether alchemy. Mine Alchemical Fragment Ore, bind shards into blocks, infuse a Mystical Stone, and forge fireproof tools, armor, and the AE Paxel. Rare Nullite Ore yields the Nullite Amplifier and the Null Multitool.
'''

[[dependencies.alchemical_excellence]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.alchemical_excellence]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
