modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="alchemical_excellence"
version="1.0.0"
displayName="Alchemical Excellence"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="OfficiallySp777"

[[dependencies.alchemical_excellence]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




