modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="alchemical_excellence"
version="1.0.0"
displayName="Alchemical Excellence"
credits="Created by Shane Pepperell (Sp777/OfficiallySp)"
displayURL="https://officiallysp.sytes.net"
authors="OfficiallySp"
description='''
description goes here whenever i can be bothered or not forget
'''

[[dependencies.alchemical_excellence]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




